"""empty message

Revision ID: 661410bb7c2e
Revises: 
Create Date: 2018-03-23 16:58:05.747373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661410bb7c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('submodel', sa.String(length=100), nullable=False),
    sa.Column('years', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'other', name='fueltypes'), nullable=False),
    sa.Column('fuel_consumptions', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Enum('OKKO', 'SOCAR', 'WOG', 'UKR_NAFTA', name='gasstations'), nullable=False),
    sa.Column('fuel_kind', sa.Enum('A95_PLUS', 'A95', 'A92', 'DIESEL', name='fuelkinds'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('fuel_data')
    op.drop_table('car_data')
    # ### end Alembic commands ###
